# Generated by Django 2.1.1 on 2018-09-18 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ('-start_time',), 'permissions': (('visitor_log', 'Can view visitor'),)},
        ),
    ]
